import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Satya Dev | Developer Portfolio",
  description: "Welcome to Satya Dev's developer portfolio, showcasing skills in web development, 3D, and more.",
  keywords: [
    "html",
    "css",
    "javascript",
    "c++",
    "python",
    "reactjs",
    "nextjs",
    "prisma",
    "node js",
    "n8n",
    "wordpress",
    "docker",
    "figma",
    "expressjs",
    "fastapi",
    "tailwind",
    "bootstrap",
    "sql",
    "godot",
    "git",
    "react",
    "portfolio",
    "3d-portfolio",
    "3d-website",
    "framer-motion",
    "animation",
    "typescript",
    "ui/ux",
  ] as Array<string>,
  authors: {
    name: "Satya Dev",
    url: "https://github.com/jaswanthsatyadev",
  },
} as const;
